dataset_path: jlli/JDocQA-nonbinary
task: "docvqa_ja_nonbinary"
output_type: generate_until
test_split: test
doc_to_visual: !function utils.docvqa_doc_to_visual
doc_to_text: "question"
doc_to_target: "original_answer"
generation_kwargs:
  max_new_tokens: 1024
  temperature: 0
  do_sample: False
metric_list:
  - metric: anls
    aggregation: mean
    higher_is_better: true
