dataset_path: hongfenglu/HungarianDocQA_IT_IFEvalQA_v2
dataset_name: first_sentence_after_title
task: docvqa_hu_ifeval_sentence
output_type: generate_until
test_split: test
doc_to_visual: !function utils.docvqa_doc_to_visual
doc_to_text: !function utils.docvqa_doc_to_text
doc_to_target: !function utils.docvqa_doc_to_target
generation_kwargs:
  max_new_tokens: 64
  temperature: 0
  do_sample: False
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
metric_list:
  - metric: anls
    aggregation: mean
    higher_is_better: true
